spring:
  redis:
    # Redis数据库索引（默认为 0）
    database: 0
    # Redis服务器地址
    host: 192.168.197.143
    # Redis服务器连接端口
    port: 6379
    # Redis 密码
    jedis:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
    # 连接超时时间（毫秒）
    timeout: 0
    password: 123456
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 192.168.197.143:9300
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.liangxin.qlmall_portal.bean